---
author: "Carson Sievert"
layout: page
permalink: /cv/
urlcolor: cyan
output: 
  pdf_document: 
    latex_engine: "xelatex" 
    includes:
      in_header:
       - cv-in-header.tex
      before_body: 
       - cv-before-body.tex
  html_document:
    keep_md: true
---

## Education

* Ph.D. in Statistics, Iowa State University \hfill (2016)
    * __Thesis__: [Interfacing R with Web Technologies for Interactive Graphics and Computing with Data](https://github.com/cpsievert/phd-thesis)
* M.S. in Statistics, Iowa State University \hfill (2013)
* Double B.A. in Mathematics & Economics, Saint John's University \hfill (2010)

## Experience

__Software Engineer__, [RStudio](https://www.rstudio.com/). \hfill Sept 2018 - Present

Develop and maintain software that RStudio's business model and user base depends upon, including but not limited to: [Shiny](https://shiny.rstudio.com/), [R Markdown](https://pkgs.rstudio.com/rmarkdown/), [Flexdashboard](https://pkgs.rstudio.com/flexdashboard/), [Plotly](https://plotly-r.com/), [bslib](https://rstudio.github.io/bslib/), [thematic](https://rstudio.github.io/thematic/), [shinymeta](https://rstudio.github.io/shinymeta/), etc.
  
__Principal consultant__, [Sievert Consulting LLC](https://cpsievert.me/consulting/). \hfill May 2015 - Present

Develop software and websites that enable clients to more easily explore data, for example:

* Explore association between mental disorders and medical conditions <https://como-gmc.cpsievert.me>, mortality <https://csievert.shinyapps.io/atlasdiseasemortality>, and the economy <https://csievert.shinyapps.io/mental-cost>
* Explore the societal impact of COVID-19 in North Carolina <https://carolinatracker.unc.edu/tracker>
* Explore NOAA's spatio-temporal data <https://github.com/ropensci/plotdap>

<!--
* Explore Canada's housing markets and census data <https://github.com/cpsievert/housing-data-challenge-plotly>
* Explore the Zika virus outbreak <https://github.com/cpsievert/zikar>
* Create interactive web graphics from R <https://plotly-r.com>
-->

__Research Assistant__, [Monash University](http://www.monash.edu/). \hfill September 2015 - May 2016

* Advise honors student research and present workshops on data science in R.

__Lecturer__, [Iowa State University](http://www.stat.iastate.edu/). \hfill Aug. 2011 - May 2015

* Course instructor for [Intro to Business Statistics](http://www.registrar.iastate.edu/catalog/2009-11/courses/stat.html#200).
    
__Software Developer__, [Google Summer of Code](http://www.google-melange.com/gsoc/homepage/google/gsoc2014). \hfill Summers 2014-2017

* Served as a student in summer 2014 and a mentor in subsequent years for  [__animint__](https://github.com/tdhock/animint); an R package for creating interactive web graphics.
  
__Research Intern__, [Statistics Research Department at AT&T Labs](http://stats.research.att.com/). \hfill Summer 2013

* Authored the R package [__LDAvis__](https://github.com/cpsievert/LDAvis) with [Kenny Shirley](http://www2.research.att.com/~kshirley/).

<!--	
__Data Analyst__, [Hardwick-Day Inc.](http://hardwickday.com/) \hfill Nov. 2010 - Nov. 2011

* Developed an algorithm for the company's web-based [Net Price Calculators](http://hardwickday.com/capabilities/net-price-calculator) (projected to generate over $3M in new revenue over five years).
-->

## Publications

### Books

* Carson Sievert (2020): Interactive web-based data visualization with R, plotly, and shiny. _Chapman and Hall/CRC_, <https://plotly-r.com>.

### Book chapters

* Carson Sievert and Brian Mills (2017): Using Publicly Available Baseball Data to Measure and Evaluate Pitching Performance in [Handbook of Statistical Methods and Analyses in Sports](https://www.crcpress.com/Handbook-of-Statistical-Methods-and-Analyses-in-Sports/Albert-Glickman-Swartz-Koning/p/book/9781498737364). Chapman & Hall/CRC. ISBN 9781498737364.

### Journal articles

* Natalie C. Momen et al. (2020): Association between Mental Disorders and Subsequent Medical Conditions. _New England Journal of Medicine_ <https://doi.org/10.1056/NEJMoa1915784>.
* Carson Sievert et al. (2019): Extending ggplot2 for Linked and Animated Web Graphics. _Journal of Computational and Graphical Statistics_ <https://doi.org/10.1080/10618600.2018.1513367>.
* Tal Galili et al. (2017): heatmaply: an R package for creating interactive cluster heatmaps for online publishing. _Bioinformatics_ <https://doi.org/10.1093/bioinformatics/btx657>.
* Carson Sievert and Kenny Shirley (2014): LDAvis: A Method for Visualizing and Interpreting Topics. _Workshop on Interactive Language Learning, Visualization, and Interfaces at the Association for Computational Linguistics_. <http://nlp.stanford.edu/events/illvi2014/papers/sievert-illvi2014.pdf>.
* Carson Sievert (2014): Taming PITCHf/x Data with pitchRx and XML2R. _The R Journal_ <http://journal.r-project.org/archive/2014-1/sievert.pdf>.

## Talks

Please see <https://talks.cpsievert.me>.

## Workshops

Please see <https://workshops.cpsievert.me>.

## Software

Please see <https://github.com/cpsievert>.

## Service 

* 2021 Program Chair-Elect, Section on Statistical Graphics, American Statistical Association.

## Honors & awards

* 2017 [John Chambers award](http://stat-computing.org/awards/jmc/winners.html) winner
* Invited participant of [2016 rOpenSci Unconference Australia](http://auunconf.ropensci.org/).
* Awarded first place in the [2014 statistical graphics video competition](http://web.archive.org/web/20140215133100/http://streaming.stat.iastate.edu/~dicook/video-competition/) for [this submission](http://web.archive.org/web/20160509234133/http://stat-graphics.org/movies/ldavis.html). 
* Invited participant of the [2014 rOpenSci hackathon](http://ropensci.github.io/hackathon/) (see my [blog post](https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/))
* Invited member of the National Mathematics Honor Society - Pi Mu Epsilon
* Invited member of the Economics Honor Society - Omicron Kappa Sigma
* President's scholar and Dean's List recipient
